import type { INodeProperties } from 'n8n-workflow';

export const contractorOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['contractor'] } },
		options: [
			{ name: 'Create', value: 'create', description: 'Create a new contractor', action: 'Create a contractor' },
			{ name: 'Get', value: 'get', description: 'Get a single contractor by ID', action: 'Get a contractor' },
			{ name: 'Get by Tax No', value: 'getByTaxNo', description: 'Get contractor by NIP', action: 'Get a contractor by tax no' },
			{ name: 'Get Many', value: 'getMany', description: 'Get many contractors', action: 'Get many contractors' },
			{ name: 'Search', value: 'search', description: 'Full-text search contractors', action: 'Search contractors' },
			{ name: 'Update', value: 'update', description: 'Update an existing contractor', action: 'Update a contractor' },
		],
		default: 'getMany',
	},
];

export const contractorFields: INodeProperties[] = [
	{
		displayName: 'Contractor ID',
		name: 'contractorId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['contractor'], operation: ['get', 'update'] } },
		description: 'The ID of the contractor',
	},
	{
		displayName: 'Tax No (NIP)',
		name: 'taxNo',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['contractor'], operation: ['getByTaxNo'] } },
		description: 'Tax identification number (NIP, 10 digits)',
	},
	{
		displayName: 'Search Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['contractor'], operation: ['search'] } },
		description: 'Full-text search across name, NIP, city, email, phone, and notes',
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['contractor'], operation: ['create'] } },
		description: 'Contractor name',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		default: 50,
		displayOptions: { show: { resource: ['contractor'], operation: ['getMany', 'search'] } },
		description: 'Max number of results to return',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['contractor'], operation: ['create'] } },
		options: [
			{ displayName: 'City', name: 'city', type: 'string', default: '', description: 'City' },
			{ displayName: 'Country', name: 'country', type: 'string', default: 'Polska', description: 'Country' },
			{ displayName: 'Email', name: 'email', type: 'string', default: '', description: 'Email address' },
			{ displayName: 'Note', name: 'note', type: 'string', default: '', description: 'Notes about the contractor' },
			{ displayName: 'Phone', name: 'phone', type: 'string', default: '', description: 'Phone number' },
			{ displayName: 'Post Code', name: 'post_code', type: 'string', default: '', description: 'Postal code' },
			{ displayName: 'REGON', name: 'regon', type: 'string', default: '', description: 'REGON number' },
			{ displayName: 'Street', name: 'street', type: 'string', default: '', description: 'Street address' },
			{ displayName: 'Tax No (NIP)', name: 'tax_no', type: 'string', default: '', description: 'Tax identification number' },
		],
	},
	{
		displayName: 'Update Fields (JSON)',
		name: 'updateData',
		type: 'json',
		required: true,
		default: '{}',
		displayOptions: { show: { resource: ['contractor'], operation: ['update'] } },
		description: 'Fields to update as JSON object',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['contractor'], operation: ['getMany'] } },
		options: [
			{ displayName: 'City', name: 'city', type: 'string', default: '', description: 'Filter by city' },
			{ displayName: 'Name', name: 'name', type: 'string', default: '', description: 'Filter by name (partial match)' },
			{ displayName: 'Offset', name: 'offset', type: 'number', default: 0, description: 'Number of results to skip' },
			{ displayName: 'Tax No', name: 'tax_no', type: 'string', default: '', description: 'Filter by NIP' },
		],
	},
];
