import type { INodeProperties } from 'n8n-workflow';

export const invoiceOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['invoice'] } },
		options: [
			{ name: 'Create', value: 'create', description: 'Create a new invoice', action: 'Create an invoice' },
			{ name: 'Download PDF', value: 'downloadPdf', description: 'Download invoice as PDF', action: 'Download an invoice PDF' },
			{ name: 'Get', value: 'get', description: 'Get a single invoice by ID', action: 'Get an invoice' },
			{ name: 'Get by Client', value: 'getByClient', description: 'Get invoices for a client', action: 'Get invoices by client' },
			{ name: 'Get by Client Tax No', value: 'getByClientTaxNo', description: 'Get invoices by client NIP', action: 'Get invoices by client tax no' },
			{ name: 'Get by Number', value: 'getByNumber', description: 'Get invoice by number', action: 'Get an invoice by number' },
			{ name: 'Get Many', value: 'getMany', description: 'Get many invoices with filters', action: 'Get many invoices' },
			{ name: 'Search', value: 'search', description: 'Full-text search invoices', action: 'Search invoices' },
			{ name: 'Update', value: 'update', description: 'Update an existing invoice', action: 'Update an invoice' },
		],
		default: 'getMany',
	},
];

export const invoiceFields: INodeProperties[] = [
	{
		displayName: 'Invoice ID',
		name: 'invoiceId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['invoice'], operation: ['get', 'downloadPdf', 'update'] } },
		description: 'The ID of the invoice',
	},
	{
		displayName: 'Invoice Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['invoice'], operation: ['getByNumber'] } },
		description: 'The invoice number to search for',
	},
	{
		displayName: 'Client ID',
		name: 'clientId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['invoice'], operation: ['getByClient'] } },
		description: 'The client ID in Fakturownia',
	},
	{
		displayName: 'Client Tax No (NIP)',
		name: 'taxNo',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['invoice'], operation: ['getByClientTaxNo'] } },
		description: 'Client tax identification number (NIP, 10 digits)',
	},
	{
		displayName: 'Search Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['invoice'], operation: ['search'] } },
		description: 'Full-text search across invoice number, client name, items, and notes',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		default: 50,
		displayOptions: { show: { resource: ['invoice'], operation: ['getMany', 'getByClient', 'getByClientTaxNo', 'search'] } },
		description: 'Max number of results to return',
	},
	// --- Create fields ---
	{
		displayName: 'Create Fields (JSON)',
		name: 'createData',
		type: 'json',
		required: true,
		default: '{"client_id":0,"positions":[{"name":"Service","quantity":1,"total_price_gross":"100","tax":"23"}]}',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
		description: 'Invoice data as JSON. Must include client_id and positions array.',
	},
	// --- Update fields ---
	{
		displayName: 'Update Fields (JSON)',
		name: 'updateData',
		type: 'json',
		required: true,
		default: '{}',
		displayOptions: { show: { resource: ['invoice'], operation: ['update'] } },
		description: 'Fields to update as JSON object',
	},
	// --- Get Many filters ---
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['invoice'], operation: ['getMany'] } },
		options: [
			{ displayName: 'Client ID', name: 'client_id', type: 'number', default: 0, description: 'Filter by client ID' },
			{ displayName: 'Currency', name: 'currency', type: 'string', default: '', description: 'Filter by currency (PLN, EUR, USD)' },
			{ displayName: 'Date From', name: 'date_from', type: 'string', default: '', placeholder: '2024-01-01', description: 'Filter from date (YYYY-MM-DD)' },
			{ displayName: 'Date To', name: 'date_to', type: 'string', default: '', placeholder: '2024-12-31', description: 'Filter until date (YYYY-MM-DD)' },
			{
				displayName: 'Income', name: 'income', type: 'options', default: '',
				options: [{ name: 'Yes (Sales)', value: 'yes' }, { name: 'No (Costs)', value: 'no' }],
				description: 'Filter by income type: yes = sales invoices, no = cost invoices',
			},
			{
				displayName: 'Kind', name: 'kind', type: 'options', default: '',
				options: [
					{ name: 'VAT Invoice', value: 'vat' }, { name: 'Pro Forma', value: 'proforma' },
					{ name: 'Receipt', value: 'receipt' }, { name: 'Estimate', value: 'estimate' },
					{ name: 'Advance', value: 'advance' }, { name: 'Final', value: 'final' },
					{ name: 'Correction', value: 'correction' },
				],
				description: 'Filter by document type',
			},
			{ displayName: 'Offset', name: 'offset', type: 'number', default: 0, description: 'Number of results to skip' },
			{
				displayName: 'Paid', name: 'paid', type: 'options', default: '',
				options: [{ name: 'Paid', value: 1 }, { name: 'Unpaid', value: 0 }],
				description: 'Filter by payment status',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['invoice'], operation: ['getByClient', 'getByClientTaxNo', 'search'] } },
		options: [
			{ displayName: 'Date From', name: 'date_from', type: 'string', default: '', placeholder: '2024-01-01', description: 'Filter from date (YYYY-MM-DD)' },
			{ displayName: 'Date To', name: 'date_to', type: 'string', default: '', placeholder: '2024-12-31', description: 'Filter until date (YYYY-MM-DD)' },
			{ displayName: 'Offset', name: 'offset', type: 'number', default: 0, description: 'Number of results to skip' },
		],
	},
];
