import type { INodeProperties } from 'n8n-workflow';

export const productOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['product'] } },
		options: [
			{ name: 'Create', value: 'create', description: 'Create a new product', action: 'Create a product' },
			{ name: 'Delete', value: 'delete', description: 'Delete a product', action: 'Delete a product' },
			{ name: 'Get', value: 'get', description: 'Get a product by ID', action: 'Get a product' },
			{ name: 'Get by Code', value: 'getByCode', description: 'Get product by code/SKU', action: 'Get a product by code' },
			{ name: 'Get Many', value: 'getMany', description: 'Get many products', action: 'Get many products' },
			{ name: 'Search', value: 'search', description: 'Full-text search products', action: 'Search products' },
			{ name: 'Update', value: 'update', description: 'Update an existing product', action: 'Update a product' },
		],
		default: 'getMany',
	},
];

export const productFields: INodeProperties[] = [
	{
		displayName: 'Product ID',
		name: 'productId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['product'], operation: ['get', 'update', 'delete'] } },
		description: 'The ID of the product',
	},
	{
		displayName: 'Product Code',
		name: 'code',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['product'], operation: ['getByCode'] } },
		description: 'Product code/SKU to search for',
	},
	{
		displayName: 'Search Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['product'], operation: ['search'] } },
		description: 'Full-text search across product fields',
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['product'], operation: ['create'] } },
		description: 'Product name',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		default: 50,
		displayOptions: { show: { resource: ['product'], operation: ['getMany', 'search'] } },
		description: 'Max number of results to return',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['product'], operation: ['create'] } },
		options: [
			{ displayName: 'Code', name: 'code', type: 'string', default: '', description: 'Product code/SKU' },
			{ displayName: 'Description', name: 'description', type: 'string', default: '', description: 'Product description' },
			{ displayName: 'Net Price', name: 'price_net', type: 'string', default: '', description: 'Net price' },
			{ displayName: 'Tax', name: 'tax', type: 'string', default: '23', description: 'Tax rate (e.g. 23)' },
			{ displayName: 'Unit', name: 'quantity_unit', type: 'string', default: 'szt.', description: 'Unit of measure' },
		],
	},
	{
		displayName: 'Update Fields (JSON)',
		name: 'updateData',
		type: 'json',
		required: true,
		default: '{}',
		displayOptions: { show: { resource: ['product'], operation: ['update'] } },
		description: 'Fields to update as JSON object',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['product'], operation: ['getMany'] } },
		options: [
			{ displayName: 'Offset', name: 'offset', type: 'number', default: 0, description: 'Number of results to skip' },
		],
	},
];
